"""initial schema

Revision ID: 4be94886b027
Revises:
Create Date: 2026-09-05 22:02:57.443283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = "4be94886b027"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector must exist before any VECTOR column is created. The compose init
    # script also does this, but a migration run against a fresh/managed database
    # cannot rely on that.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "processing", "completed", "failed", name="job_status"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("jd_text", sa.Text(), nullable=False),
        sa.Column("jd_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("total_resumes", sa.Integer(), nullable=False),
        sa.Column("processed_resumes", sa.Integer(), nullable=False),
        sa.Column("failed_resumes", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("raw_file_key", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "processed", "failed", name="candidate_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("parsed_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("education", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("experience", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidates_job_id"), "candidates", ["job_id"], unique=False)
    op.create_index(op.f("ix_candidates_status"), "candidates", ["status"], unique=False)
    op.create_table(
        "scoring_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("jd_text", sa.Text(), nullable=False),
        sa.Column("jd_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("required_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("w_skill", sa.Float(), nullable=False),
        sa.Column("w_semantic", sa.Float(), nullable=False),
        sa.Column("is_initial", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scoring_runs_job_id"), "scoring_runs", ["job_id"], unique=False)
    op.create_table(
        "scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("skill_score", sa.Float(), nullable=False),
        sa.Column("semantic_score", sa.Float(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("matched_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["scoring_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "candidate_id", name="uq_scores_run_candidate"),
    )
    op.create_index(op.f("ix_scores_candidate_id"), "scores", ["candidate_id"], unique=False)
    op.create_index(op.f("ix_scores_job_id"), "scores", ["job_id"], unique=False)
    op.create_index(op.f("ix_scores_rank"), "scores", ["rank"], unique=False)
    op.create_index(op.f("ix_scores_run_id"), "scores", ["run_id"], unique=False)
    # ### end Alembic commands ###

    # Cosine-distance ANN indexes (spec section 4). HNSW gives better recall than
    # ivfflat and needs no training pass over existing rows.
    #
    # Only the candidates index is load-bearing: ranking searches many resume vectors
    # against one JD vector. The jd_embedding indexes exist for symmetry and for
    # future "find similar job descriptions" queries; those tables hold one row per
    # job, so the index costs little either way.
    op.execute(
        "CREATE INDEX ix_candidates_embedding_cosine ON candidates "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_jobs_jd_embedding_cosine ON jobs "
        "USING hnsw (jd_embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_scoring_runs_jd_embedding_cosine ON scoring_runs "
        "USING hnsw (jd_embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_scoring_runs_jd_embedding_cosine")
    op.execute("DROP INDEX IF EXISTS ix_jobs_jd_embedding_cosine")
    op.execute("DROP INDEX IF EXISTS ix_candidates_embedding_cosine")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scores_run_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_rank"), table_name="scores")
    op.drop_index(op.f("ix_scores_job_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_candidate_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_scoring_runs_job_id"), table_name="scoring_runs")
    op.drop_table("scoring_runs")
    op.drop_index(op.f("ix_candidates_status"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_job_id"), table_name="candidates")
    op.drop_table("candidates")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###

    # Postgres keeps enum types after their tables are dropped.
    sa.Enum(name="candidate_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="job_status").drop(op.get_bind(), checkfirst=True)
